export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER"
export const ADD_MANY_CUSTOMERS = "ADD_MANY_CUSTOMERS"
export const REMOVE_MANY_CUSTOMERS = "REMOVE_MANY_CUSTOMERS"